# Generated by Django 3.1.7 on 2021-03-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_contact_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Enquiry Contacts'},
        ),
    ]
