# Generated by Django 3.1.7 on 2021-03-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210312_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='two_factor_authentication',
            new_name='two_factor_auth',
        ),
    ]
