# Generated by Django 3.1.7 on 2021-03-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210313_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='full_name'),
        ),
    ]
