# Generated by Django 3.1.7 on 2021-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210323_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='waveline/blog_photos/', width_field='width_field'),
        ),
    ]
